export const Data = [
  {
    name: 'Arun',
    gender: 'MALE',
    physics: 88,
    maths: 87,
    english: 78,
  },
  {
    name: 'Rajesh',
    gender: 'MALE',
    physics: 96,
    maths: 100,
    english: 95,
  },
  {
    name: 'Moorthy',
    gender: 'MALE',
    physics: 89,
    maths: 90,
    english: 70,
  },
  {
    name: 'Raja',
    gender: 'MALE',
    physics: 30,
    maths: 25,
    english: 40,
  },
  {
    name: 'Usha',
    gender: 'FEMALE',
    physics: 67,
    maths: 45,
    english: 78,
  },
  {
    name: 'Priya',
    gender: 'FEMALE',
    physics: 56,
    maths: 46,
    english: 78,
  },
  {
    name: 'Sundar',
    gender: 'MALE',
    physics: 12,
    maths: 67,
    english: 67,
  },
  {
    name: 'Kavitha',
    gender: 'FEMALE',
    physics: 78,
    maths: 71,
    english: 67,
  },
  {
    name: 'Dinesh',
    gender: 'MALE',
    physics: 56,
    maths: 45,
    english: 67,
  },
  {
    name: 'Hema',
    gender: 'FEMALE',
    physics: 71,
    maths: 90,
    english: 23,
  },
  {
    name: 'Gowri',
    gender: 'FEMALE',
    physics: 100,
    maths: 100,
    english: 100,
  },
  {
    name: 'Ram',
    gender: 'MALE',
    physics: 78,
    maths: 55,
    english: 47,
  },
  {
    name: 'Murugan',
    gender: 'MALE',
    physics: 34,
    maths: 89,
    english: 78,
  },
  {
    name: 'Jenifer',
    gender: 'FEMALE',
    physics: 67,
    maths: 88,
    english: 90,
  },
];
